training_pipeline_config:
    pipeline: US_VISA
    artifact_dir: artifact


data_ingestion_config:
  data_set_download_url: "url"
  raw_data_dir: raw_data
  ingested_dir: ingested_data
  ingested_train_dir: train
  ingested_test_dir: test

from our client:


data_validation_config:
  schema_dir: config
  schema_file_dir: schema


data_transformation_config:

